[project]
name = "projeto-kmeans"
version = "0.1.0"
description = ""
authors = [
    {name = "Murilo Francelino",email = "murilo_54@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn (>=1.6.1,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)"
]

[tool.poetry]
packages = [{include = "projeto_kmeans", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
